spring:
  application:
    name: consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500

server:
  port: 2001

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1001/eureka/

from: 2222